name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install backend dependencies
        run: |
          cd customer-portal/backend
          npm install

      - name: Run backend build (if needed)
        run: |
          cd customer-portal/backend
          npm run build # If you have a build script, adjust as necessary

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install frontend dependencies
        run: |
          cd customer-portal/frontend
          npm install

      - name: Run frontend build (if needed)
        run: |
          cd customer-portal/frontend
          npm run build # Adjust as necessary for your frontend
